# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zagents < Formula
  desc "ZAgents CLI — local agent runtime and management tool (Multica fork)"
  homepage "https://github.com/ZurabDev/multica"
  version "0.4.32-mz.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZurabDev/zagents-releases/releases/download/v0.4.32-mz.1/zagents-cli-0.4.32-mz.1-darwin-amd64.tar.gz"
      sha256 "5dbcc668a450957179e9604db98e59718e8ecdea2e5b9aaafbc9de089862d75d"

      define_method(:install) do
        bin.install "zagents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZurabDev/zagents-releases/releases/download/v0.4.32-mz.1/zagents-cli-0.4.32-mz.1-darwin-arm64.tar.gz"
      sha256 "d9a0ef3f098842a212d892586fde7597ebc597d17d7de895820f3b33728c9ed9"

      define_method(:install) do
        bin.install "zagents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZurabDev/zagents-releases/releases/download/v0.4.32-mz.1/zagents-cli-0.4.32-mz.1-linux-amd64.tar.gz"
      sha256 "33e0e5fd65d137364c5c512fa70a0277174a703bc9a213f209873c311dac5785"
      define_method(:install) do
        bin.install "zagents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZurabDev/zagents-releases/releases/download/v0.4.32-mz.1/zagents-cli-0.4.32-mz.1-linux-arm64.tar.gz"
      sha256 "2f0254633aaedc5a184b2798f6cae661f9e2df80eb177ab92a9b81bc0d92c3d5"
      define_method(:install) do
        bin.install "zagents"
      end
    end
  end

  test do
    system "#{bin}/zagents", "version"
  end
end
